seed: 2025

num_workers: 4
experiment_name: "mmdet_centernet"

dataset:
  n_splits: 5
  fold_th: 0

model:
  mmdet_config_path: ./config/base_centernet.py
  num_classes: 1

trainer:
  devices: [0]
  max_epochs: 100

train_parameters:
  batch_size: &batch_size 8

val_parameters:
  batch_size: *batch_size

output_root_dir: experiments
checkpoints_dir: checkpoints
