seed: 2025

num_workers: 4
experiment_name: "mmdet_centernet_rexnet_150_merged_dataset"

dataset:
  n_splits: 5
  fold_th: 0

model:
  mm_config_path: ./config/centernet_rexnet_150_merged_dataset.py
  num_classes: 1
  checkpoints:

trainer:
  devices: [0]
  max_epochs: 20

train_parameters:
  batch_size: &batch_size 8

val_parameters:
  batch_size: *batch_size

output_root_dir: experiments
checkpoints_dir: checkpoints
